# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            Repeat
tagline:          'ing'
description:      '还没想好怎么写'
url:              http://ppggff.github.io/ 
paginate:         1
baseurl:          /

author:
  name:           'bane'
  url:            http://weibo.com/234305250

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
